# Project - 1
## NumPy Data Explorer
- Learned NumPy fundamentals – array creation, indexing, and slicing.
- Performed mathematical, axis-wise, and statistical operations on datasets.
- Applied reshaping and broadcasting techniques for efficient computation.
- Implemented save/load operations for NumPy arrays.
- Compared NumPy’s performance with standard Python lists.

In [1]:
import numpy as np
import time

### Array creation

In [2]:
data = np.array([
    [41, 84, 92],
    [25, 88, 88],
    [34, 72, 72],
    [12, 91, 81]])
print(data)

[[41 84 92]
 [25 88 88]
 [34 72 72]
 [12 91 81]]


### Indexing and Slicing

In [3]:
print("First Row:")
print(data[0])

First Row:
[41 84 92]


In [4]:
print("Second Column:")
print(data[:, 1])

Second Column:
[84 88 72 91]


In [5]:
print("First Two Rows:")
print(data[:2])

First Two Rows:
[[41 84 92]
 [25 88 88]]


###  Mathematical Operations

In [6]:
print("Dataset + 10:")
print(data + 10)

Dataset + 10:
[[ 51  94 102]
 [ 35  98  98]
 [ 44  82  82]
 [ 22 101  91]]


In [7]:
print("Dataset Squared:")
print(data ** 2)

Dataset Squared:
[[1681 7056 8464]
 [ 625 7744 7744]
 [1156 5184 5184]
 [ 144 8281 6561]]


### AXIS-WISE OPERATIONS

In [8]:
print("Row-wise Sum:")
print(np.sum(data, axis=1))

Row-wise Sum:
[217 201 178 184]


In [9]:
print("Column-wise Sum:")
print(np.sum(data, axis=0))

Column-wise Sum:
[112 335 333]


### Statistical Operations

In [10]:
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Maximum:", np.max(data))
print("Minimum:", np.min(data))
print("Standard Deviation:", np.std(data))

Mean: 65.0
Median: 76.5
Maximum: 92
Minimum: 12
Standard Deviation: 27.57414247684474


###  Reshaping

In [11]:
reshaped = data.reshape(2, 6)
print("Reshaped Array (2x6):")
print(reshaped)

Reshaped Array (2x6):
[[41 84 92 25 88 88]
 [34 72 72 12 91 81]]


### Broadcasting

In [12]:
bonus_marks = np.array([5, 3, 2])
updated_scores = data + bonus_marks
print("After Broadcasting Bonus Marks:")
print(updated_scores)

After Broadcasting Bonus Marks:
[[46 87 94]
 [30 91 90]
 [39 75 74]
 [17 94 83]]


### Save and Load Arrays

In [13]:
np.save("student_scores.npy", data)
loaded_data = np.load("student_scores.npy")
print("\nLoaded Data:")
print(loaded_data)


Loaded Data:
[[41 84 92]
 [25 88 88]
 [34 72 72]
 [12 91 81]]


### Numpy vs Python list Performance

In [14]:
size = 1_000_000
# Python List
py_list = list(range(size))
start = time.time()
py_result = [x * 2 for x in py_list]
python_time = time.time() - start
# NumPy Array
np_array = np.arange(size)
start = time.time()
np_result = np_array * 2
numpy_time = time.time() - start

print("Performance Comparison")
print(f"Python List Time : {python_time:.6f} seconds")
print(f"NumPy Array Time : {numpy_time:.6f} seconds")

if numpy_time < python_time:
    print("NumPy is faster.")
else:
    print("Python list is faster.")

Performance Comparison
Python List Time : 0.044308 seconds
NumPy Array Time : 0.003431 seconds
NumPy is faster.
